---
layout: mypost
title: java.lang.NoSuchFieldError 错误处理
categories: [JAVA]
---

## 故事背景

程序在文件上传转换时，报了一个错误：Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES

具体报错信息：
>Caused by: java.lang.NoSuchFieldError: WORKBOOK_DIR_ENTRY_NAMES  
	at org.apache.tika.detect.microsoft.POIFSContainerDetector.detect(POIFSContainerDetector.java:292)  
	at org.apache.tika.parser.microsoft.OfficeParser$POIFSDocumentType.detectType(OfficeParser.java:354)  
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:214)  
	at org.apache.tika.parser.microsoft.OfficeParser.parse(OfficeParser.java:183)  

报错位置：
````java
	private static FileContentTypeDTO parseMetadata(InputStream inputstream, Parser parser, Map<String ,String> map) {
		BodyContentHandler handler = new BodyContentHandler();
		Metadata metadata = new Metadata(); // empty metadata object
		ParseContext context = new ParseContext();
		try {
			parser.parse(inputstream, handler, metadata, context);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (TikaException e) {
			e.printStackTrace();
		} catch (SAXException e) {
			e.printStackTrace();
		} finally {
			try {
				if(inputstream != null) {
					inputstream.close();
				}
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		String mimeType = metadata.get(HttpHeaders.CONTENT_TYPE);
		System.out.println("---------- metadata mimeType is " + mimeType);
		if (map.containsKey(mimeType)) {
			return FileContentTypeDTO.builder()
					.contentType(mimeType)
					.fileExtName(map.get(mimeType))
					.accuracy(100)
					.build();
		}
		return null;
	}

````

## 问题处理

### 希望能catch住异常

从代码上看有一堆catch 依然没有把异常catch住， 程序出现异常后直接中断了， 不再继续执行了，本意是希望能catch异常，外部使用的地方其实加了兜底方案

于是乎又加了一个catch
````java
		try {
			parser.parse(inputstream, handler, metadata, context);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (TikaException e) {
			e.printStackTrace();
		} catch (SAXException e) {
			e.printStackTrace();
    } catch (Exception e) {
			e.printStackTrace();
		} finally {
			try {
				if(inputstream != null) {
					inputstream.close();
				}
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
````

结果依然抛出异常中断执行，然后查看  Exception 发现

> public class Exception extends Throwable {

Exception 继承于 Throwable 还不是最基础的类（过去一直以为Exception就是最底层的了）

于是又改了， 使用了 catch (Throwable t)

````java
		try {
			parser.parse(inputstream, handler, metadata, context);
		} catch (IOException e) {
			e.printStackTrace();
		} catch (TikaException e) {
			e.printStackTrace();
		} catch (SAXException e) {
			e.printStackTrace();
    } catch (Throwable t) {
			t.printStackTrace();
		} finally {
			try {
				if(inputstream != null) {
					inputstream.close();
				}
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
````

问题解决， 异常会被打印， 但是程序会继续执行，符合预期

### 知识点：异常(Throwable)

Throwable： 有两个重要的子类：Exception（异常）和 Error（错误），二者都是 Java 异常处理的重要子类，各自都包含大量子类。
 Error（错误）:是程序无法处理的错误，表示运行应用程序中较严重问题。大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。
 Exception（异常）:是程序本身可以处理的异常。(如下)

运行时异常：都是RuntimeException类及其子类异常，如NullPointerException(空指针异常)、IndexOutOfBoundsException(下标越界异常)运行中出现“除数为0”错误，引发ArithmeticException异常等，
这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生。
非运行时异常 （编译异常）：是RuntimeException以外的异常，类型上都属于Exception类及其子类。从程序语法角度讲是必须进行处理的异常，如果不处理，程序就不能编译通过。
如IOException、SQLException等以及用户自定义的Exception异常，一般情况下不自定义检查异常。

异常处理机制为：抛出异常，捕捉异常。一个方法所能捕捉的异常，一定是Java代码在某处所抛出的异常。简单地说，异常总是先被抛出，后被捕捉的。
抛出异常：当一个方法出现错误引发异常时，方法创建异常对象并交付运行时系统，异常对象中包含了异常类型和异常出现时的程序状态等异常信息。
运行时系统负责寻找处置异常的代码并执行。
无论是谁，都可以通过Java的throw(一定抛出)语句抛出异常。从方法中抛出的任何异常都必须使用throws(可能抛出)子句。

捕获异常：在方法抛出异常之后，运行时系统将转为寻找合适的异常处理器（exception handler）。
捕捉异常通过try-catch语句try-catch-finally语句实现。
finally里是必定执行的代码，即使try里使用了return。
以下4种特殊情况下，finally块不会被执行：
1）在finally语句块中发生了异常。
2）在前面的代码中用了System.exit()退出程序。
3）程序所在的线程死亡。
4）关闭CPU。

## 问题的根本原因

虽然问题得到了初步解决，但是看着这个错误，感觉也不爽，感觉还是需要处理一下的

一番搜索， 网上说一般是poi包和tika包版本不兼容导致的  
经查我们使用的 apache.poi 版本是4.1.2 是2020-02-17 出的， 而 apache.tika 版本是 2.9.0 是2023.8.28发布的，相隔三年多，版本差异应该是有的

于是 把apache.poi版本升级一下， 升级到5.2.2，最终问题解决， 报错消失

pom.xml

````xml
		<dependency> 
		    <groupId>org.apache.tika</groupId> 
		    <artifactId>tika-core</artifactId> 
		    <version>2.9.0</version> 
		</dependency>
		<dependency>
			<groupId>org.apache.tika</groupId>
			<artifactId>tika-parsers-standard-package</artifactId>
			<version>2.9.0</version>
			<exclusions>
				<exclusion>
					<!-- 这个包会和jre中的java.xml包冲突，所以屏蔽掉 -->
					<groupId>xml-apis</groupId>
					<artifactId>xml-apis</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

    <dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.2</version>
		</dependency>
		<!-- poi-ooxml -->
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.2</version>
		</dependency>
````